import { auth } from "@/services/firebase";
import { signInWithEmailAndPassword } from "firebase/auth";
import type { NextApiRequest, NextApiResponse } from "next";
import { NextResponse } from "next/server";

export async function GET(req: Request, res: NextApiResponse) {
  // TODO: authentication get characters that belong to the user

  // TO DELETE
  const charactersTemplates = [
    {
      character_id: 1,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: true,
    },
    {
      character_id: 2,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: true,
    },
    {
      character_id: 3,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
    {
      character_id: 4,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
    {
      character_id: 5,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
    {
      character_id: 6,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
    {
      character_id: 7,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
    {
      character_id: 8,
      race_id: 11,
      class_id: 2,
      background_id: 9,
      name: "UserPrueba7",
      story: "Muy barbaro",
      alignment: "chaotic-good",
      age: 12,
      hair: "Negro",
      eyes: "Cafe",
      skin: "Oscura",
      height: 2,
      weight: 100,
      img: "https://dicelogger-images.s3.sa-east-1.amazonaws.com/f6bddd2f-e249-4a80-8d57-8a9d153157ca-astarion.webp",
      str: 12,
      dex: 10,
      int: 9,
      con: 12,
      wiz: 10,
      cha: 9,
      hitpoints: 8,
      hitdice: "1d8",
      speed: 30,
      armorclass: 0,
      level: 3,
      exp: 0,
      items: [],
      weapons: [],
      armor: null,
      skills: [],
      features: [],
      spells: [],
      proficiencies: [],
      pro: false,
    },
  ];

  return NextResponse.json(charactersTemplates, { status: 200 });
}
